---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mytestapp
 labels:
  app: mytestapp
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mytestapp
 template:
  metadata: 
   labels:
    app: mytestapp
  spec:
   containers:
   - name: mytestapp
     image: atulpaul73/devops:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp1
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
